# Øving 3

Vi henviser til introduksjonsforelesningen for mer informasjon.


## Nettverk, matriser og differensiallikninger

#### Flere av oppgavene i denne øvingen ber deg forklare noe. Ta med disse forklaringene inn i refleksjonsnotatet.

Vi repeterer litt fra øving 2.

Det viktigste vi lærte fra forrige øving er at "nettverk = matriser".

Hvis vi har en matrise $A$, så betyr $A[i,j]=w$ at vi har en pil fra node $i$ til node $j$ med vekt $w$. 

Vi så på et nettverk som modellerte flyt av "noe" over pilene i nettverket. I andvendelsen så var nodene websider, pilene var lenker mellom sidene og flyten var brukere som surfet gjennom nettverket ved hjelp av lenker, eller ved å hoppe til en tilfeldig side.

Vi tillot ikke løkker i modellen, men vi ville ha at radsummene var $0$, som gjorde at vi satte en negativ vekt på hver løkke.

Repeter det du gjorde på forrige øving før du går videre. Du kommer ikke til å trenge kode derifra, men du vil måtte bruke matrisen som du lagde, som du også får her:

    M = np.array([[-1.8,  1.,   0.2,  0.2,  0.2,  0.2],
         [ 0.2, -1.8,  1.,   0.2,  0.2,  0.2],
         [ 0.2,  1.,  -1.8,  0.2,  0.2,  0.2],
         [ 1.,   1.,   0.2, -2.6,  0.2,  0.2],
         [ 0.2,  1.,  0.2,  1.,  -3.4,  1. ],
         [ 0.2 , 1.,   0.2,  0.2,  1.,  -2.6]])

Vi starter som vanlig med å importere matrisebiblioteket numpy.


In [3]:
import numpy as np

## Utregning av egenverdier i numpy

En kollonnevektor $v$ er en egenvektor med tilhørende egenverdi $\lambda$ hvis $M\cdot v = \lambda \cdot v$. 
Vi sier at $v$ er en høyre egenvektor, da $v$ står til høyre for $M$.

En radvektorer $v$ er en (venstre) egenvektor hvis $v \cdot N = \lambda \cdot v$.

Vi kan bruke np.linalg.eig for å regne ut egenvektorer og egenverdier i numpy.

    import numpy as np   
    A = np.array([[1.2, 3.2], [4.1, 5.5]])
    
    # Høyre egenvektorer, dvs. egenvektorer x hvor Ax = l*x, hvor l er tilhørende egenverdi
    eigenval, eigenvec = np.linalg.eig(A)   
    
    for i in range(len(eigenval)):
        print("Egenvektor",eigenvec[:,i],"med tilhørende egenverdi",eigenval[i])
    

## Oppgave 1

Vi skal se på egenvektorer og egenverdier til en matrise. Vi jobber med radvektorer, så en rad-vektor $v$ er en (venstre) egenvektor med tilhørende egenverdi $\lambda$ hvis 

$$
v\cdot M = \lambda \cdot v
$$

Skriv kode som gjør det følgende og skriver svarene til konsollet:

a) Regn ut egenverdier og (venstre) egenvektorer til matrisen i siste oppgave fra øving 2 og skriv ut disse til konsollet.

b) Hvilken egenverdi har størst absoluttverdi? Skriv et program som finner indeksen til denne egenverdien hvor du bruker svaret fra a)

c) Hva er egenvektoren som passer til egenvektoren i b)? Skriv ut egenverdien til konsollet.

d) Regn ut de høyre egenvektorene med tilhørende egenverdier (dvs. $M\cdot v = \lambda \cdot v$) og skriv disse ut til konsollet. 

e) Hva er sammenhengen mellom egenverdiene fra a) og i d)?

f) La maxi være indeksen du fant fra oppgave b). Vi har at $v\cdot M - \lambda \cdot v $ er lik null-vektor. Men når jeg kjører

    print( eigenvec[:,maxi] @ M - eigenval[maxi] * eigenvec[:,maxi] )
    
så får jeg ikke 0-vektor som svar. Hva kan være en grunn for at det skjer?



In [9]:
import numpy as np   

M = np.array([[-1.8,  1.,   0.2,  0.2,  0.2,  0.2],
 [ 0.2, -1.8,  1.,   0.2,  0.2,  0.2],
 [ 0.2,  1.,  -1.8,  0.2,  0.2,  0.2],
 [ 1.,   1.,   0.2, -2.6,  0.2,  0.2],
 [ 0.2,  1.,  0.2,  1.,  -3.4,  1. ],
 [ 0.2 , 1.,   0.2,  0.2,  1.,  -2.6]])

eigenval, eigenvec = np.linalg.eig(M.transpose())
print("Venstre egenverdier og egenvektorer til matrisen M:",M)
for i in range(len(eigenval)):
    print("Egenvektor", eigenvec[:,i], "med egenverdi",eigenval[i])
    
    
maxi = 0
for i in range(1, len(eigenval)):
    if abs(eigenval[i]) > abs(eigenval[maxi]):
        maxi = i

s = sum(eigenvec[:,0])
print("HERE",s, " ", eigenvec[:,0] / s)
    
print("Egenverdien med størst absoluttverdi er ", eigenval[maxi],"og denne har egenverdi",eigenvec[:,maxi])


eigenval, eigenvec = np.linalg.eig(M)
print("Høyre egenverdier og egenvektorer til matrisen M:",M)
for i in range(len(eigenval)):
    print("Egenvektor", eigenvec[:,i], "med egenverdi",eigenval[i])
            
print("Egenverdien med størst absoluttverdi er ", eigenval[maxi],"og denne har egenverdi",eigenvec[:,maxi])


Venstre egenverdier og egenvektorer til matrisen M: [[-1.8  1.   0.2  0.2  0.2  0.2]
 [ 0.2 -1.8  1.   0.2  0.2  0.2]
 [ 0.2  1.  -1.8  0.2  0.2  0.2]
 [ 1.   1.   0.2 -2.6  0.2  0.2]
 [ 0.2  1.   0.2  1.  -3.4  1. ]
 [ 0.2  1.   0.2  0.2  1.  -2.6]]
Egenvektor [0.28715587 0.74701041 0.50796708 0.19498238 0.15953104 0.19498238] med egenverdi 0.0
Egenvektor [-1.75001569e-01  2.34566864e-16 -3.09456041e-16  4.58160055e-01
 -7.41318541e-01  4.58160055e-01] med egenverdi -4.094427190999907
Egenvektor [ 1.46488200e-15  7.07106781e-01 -7.07106781e-01 -8.47554534e-17
  4.96125971e-16 -4.57480820e-16] med egenverdi -2.7999999999999967
Egenvektor [ 7.07106781e-01  1.26812892e-15 -7.07106781e-01 -3.24413035e-16
  3.22189942e-16 -2.42251044e-17] med egenverdi -2.0000000000000018
Egenvektor [ 8.61453263e-01 -8.32359292e-16  9.91792170e-16 -3.29045867e-01
 -2.03361529e-01 -3.29045867e-01] med egenverdi -2.305572809000084
Egenvektor [ 7.02770369e-01  7.81908502e-02 -7.81908502e-02 -7.02770369e-01
  

Vi har de samme egenverdiene til høyre og venstre, men egenvektorene er ikke nødvendigvis like.

Grunnen til at jeg ikke får 0 er avrundingsfeil i beregningen. Tallene er nære, men ikke helt lik 0.

## Oppgave 2 (En enkel algoritme for å en egenvektor/egenverdi)
 
Denne oppgaven er litt annerledes. Her skal vi gi dere et lite program som regner ut egenverdi med størst absoluttverdi (fra forrige oppgave). 

I programmet så lager vi en tilfeldig vektor, gjentar beregningen $v = v \cdot M$ mange ganger Underveis regner vi $v = v / abssum$ for å hindre at tallene i vektoren blir alt for store. Til slutt finner vi egenverdien.

Dere skal finne ut hvorfor programmet fungerer og svare på spørsmålene under.

    from random import random

    v = np.zeros(6)
    for i in range(6):
        v[i] = random()
    
    
    for i in range(100001):
        v = v @ M
        abssum = sum(abs(v))
        v = v / abssum
 
    l = (v @ M)[1]/v[1]
    print(l)


Svaret som skrives ut er lik egenverdien med størst absoluttverdi. Vektoren $v$ er den tilhørende egenvektoren.

a) Forklar hvorfor denne beregningen fungerer? Hvis du ikke klarer dette på egenhånd, så kan du google "Power Iteration Eigenvalue Algorithm" for å få mer informasjon.

b) Vi har fylt vektoren $v$ med tilfeldige tall. Hvis vi er skikkelig uheldig, så vil vi ikke finne frem til den største egenverdien her. Gi et eksempel på en vektor $v$ hvor beregningen ikke vil fungere. 


In [5]:
from random import random

# Vi fyller vektoren med (pseudo)tilfeldig valgte tall
v = np.zeros(6)
for i in range(6):
    v[i] = random()
    
for i in range(100001):
    v = v @ M
    abssum = sum(abs(v))
    v = v / abssum
 
l = (v @ M)[1]/v[1]
print(l)



-4.094427190999916


Vi har $v = v_1 + \cdots + v_r$ for egenvektorer $v_i$, og $v \cdot M^n = v = \lambda_1^n \cdot v_1 + \cdots + \lambda_r^n \cdot v_n$. Hvis $\lambda_1$ er egenverdi med størst absoluttveri $\lambda_1^n$ dominere og være mye større enn alle andre $\lambda_i^n$. Etter normalisering så vil $v\cdot M^n$ være (omtrent) en egenverdi for egenverdien $\lambda_1$. Vi har $v\cdot M = \lambda_1\cdot v$, slik at $l$ blir lik egenverdien $\lambda$.

Enhver egenvektor som ikke er $v_1$ vil være et eksempel på en $v$ hvor dette ikke fungerer.



## Oppgave 3

Vi fortsetter med matrisen fra slutten av øving 2. Fra Oppgave 1, så bør du ha funnet en egenverdi lik $0$.

a) Fra Oppgave 1 så har du funnet en egenvektor som passer til egenverdien $0$. Men det finnes mange andre egenvektorer
til $0$. Lag et kort program som skriver ut $20$ forskjellige egenvektorer til egenverdien $0$.

b) Det finnes en unik egenvektor til egenverdien $0$ slik at summen i tallene i egenvektoren er lik $1$. Hva er denne egenvektoren?

c) Sammenlign svaret fra a) og resultatet fra Euler integrasjonen av webmodellen i Øving 2. Hvis du har regnet riktig begge ganger, så skal svarene være like. 

Forklar hvorfor disse tallene er like. Her vil du måtte bruke ting du har lært om egenverdier og lineære differensiallikninger fra forelesningene. 



a) De kan skrive ut $a\cdot v$ hvor $v$ er svaret fra Oppgave 1 og $a=1,2,3,\cdot,20$.

b) [0.13728814 0.35714286 0.24285714 0.09322034 0.07627119 0.09322034]

c) Henviser til forelesningene