# Ellipsoiden

## Diagonalisering og ellipsoiden

La oss ta et koordinatsystem $(\vec{x},\vec{y},\vec{z})$ hvor $\vec{y}$ peker mot sola, $\vec{x}$ ligger i planet av jordens bane rundt sola, og peker i retning av jordens bevegelse, og $\vec{z} = \vec{x}\times\vec{y}$.

Ellipsoiden defineres av løsninger til $\vec{r}^T A \vec{r} = 1$, hvor 

$$
A = \begin{pmatrix}
1.456\cdot 10^{-7} & 1.122\cdot 10^{-8} & -3.648\cdot 10^{-8} \\
1.122\cdot 10^{-8} & 1.456\cdot 10^{-7} & 3.648\cdot 10^{-8} \\
-3.648\cdot 10^{-8} & 3.648\cdot 10^{-8} & 3.814\cdot 10^{-8}
\end{pmatrix}.
$$

Ellipsoide? Ligning av en ellipsoide er

$$
\frac{x^2}{a^2} + \frac{y^2}{b^2} + \frac{z^2}{c^2} = 1,
$$

hvor $a, b, c$ er lengde av "semi-aksene", altså avstand fra origo til overflaten langs henholdsvis $x-, y-$ og $z-$aksene.

## Oppgave 1

1. Bruk koden under til å diagonalisere systemet
2. Egenverdiene $(\lambda_1, \lambda_2, \lambda_3)$ er relatert til (cirka) avstand fra jordens sentrum til havnivået i forskjellige retninger. Stemmer verdiene overens med det du finner på nett?
3. Egenvektorene $(\vec{v}_1, \vec{v}_2, \vec{v}_3)$ danner en ny basis. Hvor peker koordinatsystemet? Sammenlign med den opprinnelige basisen $(\vec{x},\vec{y},\vec{z})$.

In [9]:
import numpy as np

A = np.array([[ 1.45572807e-07,  1.12161546e-08, -3.64801898e-08],
 [ 1.12161546e-08,  1.45572807e-07,  3.64801898e-08],
 [-3.64801898e-08,  3.64801898e-08,  3.81382932e-08]])

everdier, evektorer = np.linalg.eig(A)

print(everdier)

print(evektorer)

[1.57059839e-08 1.56788962e-07 1.56788962e-07]
[[-2.81958172e-01 -6.48459435e-01 -7.07106751e-01]
 [ 2.81958172e-01  6.48459359e-01 -7.07106811e-01]
 [-9.17060074e-01  3.98749070e-01 -1.84667538e-08]]


## Treghetsmoment og "Chandler wobble"

Eulers ligning forklarer rotasjon til et stivt legeme. Den sier at 

\begin{align*}
I_1 \dot{\omega}_1 & = \omega_2 \omega_3 (I_1 - I_3) \\
I_2 \dot{\omega}_2 & = -\omega_1 \omega_3 (I_1 - I_3) \\
I_3 \dot{\omega}_3 & = \omega_1 \omega_2 (I_2 - I_3)
\end{align*}

Her er $\vec{\omega}$ vinkelhastighet: det betyr at legemet roterer rundt en akse som peker i retning $\vec{\omega}$ med hastighet $|\vec{\omega}|$.

Treghetsmoment til en solid ellipsoide (i basisen som diagonaliserer ellipsoiden) med masse $m$ er

$$
I_1 = \frac{m}{5}(b^2 + c^2), \quad
I_2 = \frac{m}{5}(a^2 + c^2), \quad
I_3 = \frac{m}{5}(a^2 + b^2).
$$

I dette tilfellet, du burde finne at den tredje ligningen blir $\dot{\omega}_3 = 0$, altså at $\omega_3$ er konstant. De andre to kan kombineres: la $\Omega = \omega_3(I_1 - I_3)/I_1$, da får vi

$$
\begin{pmatrix}
\dot{\omega}_1 \\
\dot{\omega}_2
\end{pmatrix}
=
\begin{pmatrix}
0 & \Omega \\
-\Omega & 0
\end{pmatrix}
\begin{pmatrix}
\omega_1 \\
\omega_2
\end{pmatrix}
$$

Hvis $\omega_1(0)=\omega_2(0)=0$, vil de forblir null for alle tid. Da får vi ren rotasjon rundt $z$-aksen, med vinkelhastighet $\omega_3$. Det er sikkert hvordan vi tenker på jordens rotasjon. Poenget er at det vil være tendenser til små endringer i jordens rotasjonsakse, siden $\omega_1, \omega_2$ i praksis er liten men ikke helt lik null.


## Oppgave 2

1. Hva er $\omega_3$? (tenk på hva som skjer hvis $\omega_1 = \omega_2 = 0$. Det er et kjent tall!)
2. Diagonaliser systemet for $\omega_1, \omega_2$. Hva blir den generelle løsningen?
3. Bruk dataen fra ellipsoiden til å bestemme $\Omega$, og derved perioden til jordens "wobble". Euler (1749) beregnet det til å være cirka 300 dager. Er du enig?
4. Den ekte verdien (Chandler, 1891) virker å være cirka 429 dager. Hvorfor tror du det er annerledes? (Hint: det er til en viss grad et åpent spørsmål! Men prøv å identifisere noen årsaker til avvik)

## Løsning

1. Det er 1/døgn, men hva slags døgn? Et siderisk døgn (https://no.wikipedia.org/wiki/Siderisk_tid)! Dvs cirka 1/86 164,1 sekunder. Hadde du et soldøgn på 24 timer burde du ikke være for sur!
2. Egenverdiene blir $\pm i\Omega$, med vektorene

$$
V = \begin{pmatrix}
-i & i \\
1 & 1
\end{pmatrix}
$$

Vi får altså løsninger

$$
\begin{pmatrix}
\omega_1 \\
\omega_2
\end{pmatrix}
=
C_1 \begin{pmatrix}
-i \\
1
\end{pmatrix}
e^{i\Omega t}
+ 
C_2 \begin{pmatrix}
i \\
1
\end{pmatrix}
e^{-i\Omega t}
$$

dvs perioden på en wobble blir på cirka $1/\Omega$ døgn (se under). De verdiene gir har oppgitt gir mye fortere wobble enn Euler. Trolig skyldes det en feilaktig antakelse av jevn fordeling av jordens masse i beregning av $I_i$.

In [14]:
a = 1/everdier[0]
b = 1/everdier[1]
c = 1/everdier[2]

print(a)
print(b)
print(c)

m = 5.972e24
o3 = 1/86141.1

I1 = (m/5)*(b**2 + c**2)
I2 = (m/5)*(a**2 + c**2)
I3 = (m/5)*(a**2 + b**2)

print(I1)
print(I2)
print(I3)

Omega = o3*(I1-I3)/I1

period = 1/Omega

soldøgn = 24*60*60

print(period/soldøgn)

print(I1/(I1-I3))

63670000.359642446
6378000.014166491
6378000.018593148
9.717371859831822e+37
4.8905279281926614e+39
4.8905279281252185e+39
-0.020211845529527563
-0.020272592917331928
